config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :doses, only: [:destroy]
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all # GET /restaurants
  end

  def show          # GET /restaurants/:id
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :set_dose, only: [:show, :edit, :update, :destroy]
  before_action :set_cocktail, only: [:new, :create]

  def index       # GET /restaurants
  end

  def show          # GET /restaurants/:id
  end

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit          # GET /restaurants/:id/edit
  end

  def update
  end

  def destroy
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<div class="col-xs-12 col-md-6 offset-md-3">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file, label: "Image of cocktail" %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "add a cocktail", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cocktails/index.html.erb
<h1 id="our-menu"><%= "Our Menu..." %></h1>
<br>
<div = class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-md-6 col-lg-4 offset-xs-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path cocktail.photo, height: 400, crop: :scale%>);">
          <div class="card_title">
            <h1><%= link_to cocktail.name, cocktail %></h1>
          </div>
          <div class="card_description">
            <% cocktail.doses.each do |dose| %>
              <li><%= dose.ingredient.name %></li>
            <% end %>
          </div>
          <%= link_to "", cocktail, class: "card-link"%>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="create-button">
  <%= link_to 'Create a new Cocktail', new_cocktail_path, class: "btn btn-primary btn-lg"%>
</div>

app/views/cocktails/new.html.erb
<%= render 'form' %>

app/views/cocktails/show.html.erb
<div class="cocktail-container col-xs-12 col-md-6 offset-md-3" >
  <div id="name-badge">
    <h1><%= @cocktail.name %></h1>
  </div>
  <div class="cocktail-info">
    <div class="cocktail-pic">
      <%= cl_image_tag @cocktail.photo, height: 300, crop: :scale %>
    </div>
    <div class="cocktail-bio">
      <h2>Ingredients...</h2>
      <br>
      <% @cocktail.doses.each do |dose| %>
        <h3><%= "#{dose.description} #{dose.ingredient.name}"%></h3>
        <%= link_to 'Delete dose', dose_path(dose), method: :delete %>
      <% end %>
      <br>
    </div>
  </div>
  <div class="cocktail-links">
    <%= link_to 'All Cocktails', cocktails_path %>
    <%= " | " %>
    <%= link_to 'Add dose',  new_cocktail_dose_path(@cocktail) %>
    <%= " | " %>
    <%= link_to 'Delete Cocktail', cocktail_path(@cocktail), method: :delete %>
  </div>
</div>

app/views/doses/_form.html.erb
<div class="col-xs-12 col-md-6 offset-md-3">
  <%= simple_form_for([@cocktail, @dose]) do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit "add a dose", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/doses/new.html.erb
<h2><%= "Add a dose to #{@cocktail.name}" %></h2>
<br>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif|Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/banner' %>
    <div class = "body-container">
      <%= yield %>
      <%= javascript_include_tag "application" %>
      <%= javascript_pack_tag "application" %>
    </div>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,1) 0%, rgba(129,64,64,0.5) 50%), url('https://static.independent.co.uk/s3fs-public/thumbnails/image/2018/05/22/13/gin-cocktails.jpg?w968h681);">
  <div class="banner-content">
    <h1><%= link_to 'Cocktail Smocktail Lounge', root_path %></h1>
    <p>Redefining Classy Cocktails</p>
    <div class="cocktail-button">
      <%= link_to 'Create a new Cocktail', new_cocktail_path, class: "btn btn-primary btn-lg"%>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <a href="/" class="navbar-wagon-brand">
   <%= image_tag "cocktail.png" %>
  </a>
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <a href="" class="navbar-wagon-item navbar-wagon-link">Our Mixologists</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Mixology Classes</a>
  </div>
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="">Our Mixologists</a></li>
        <li><a href="">Mixology Classes</a></li>
      </ul>
    </div>
  </div>
</div>